"""Evidence is derived from supplied context, never generated by a model."""

from __future__ import annotations

from modules.qura.schemas import Evidence, HealthContext


class EvidenceBuilder:
    def build(self, context: HealthContext) -> Evidence:
        lifestyle: list[str] = []
        if context.lifestyle is not None:
            lifestyle = [key for key, value in context.lifestyle.model_dump().items() if value is not None]
        return Evidence(
            markers=context.selected_markers,
            risks=context.risk_scores,
            history=context.deltas,
            lifestyle=lifestyle,
        )
