from __future__ import annotations

from dataclasses import dataclass
import re


@dataclass(frozen=True)
class SeedDiagnosticTestGroup:
    group_name: str


@dataclass(frozen=True)
class SeedDiagnosticPackage:
    package_name: str


@dataclass(frozen=True)
class SeedDiagnosticTest:
    test_name: str
    parameter_key: str | None
    unit: str | None
    meaning: str | None
    lower_range_male: float | None
    higher_range_male: float | None
    lower_range_female: float | None
    higher_range_female: float | None
    causes_when_high: str | None
    causes_when_low: str | None
    effects_when_high: str | None
    effects_when_low: str | None
    what_to_do_when_low: str | None
    what_to_do_when_high: str | None


def _slug_parameter_key(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "_", value)
    return value.strip("_")


DIAGNOSTIC_TEST_GROUPS: tuple[SeedDiagnosticTestGroup, ...] = (
    SeedDiagnosticTestGroup("Liver profile"),
    SeedDiagnosticTestGroup("Kidney function test"),
    SeedDiagnosticTestGroup("Kidney function test advance"),
    SeedDiagnosticTestGroup("Kidney function test with K"),
    SeedDiagnosticTestGroup("Thyroid profile"),
    SeedDiagnosticTestGroup("Iron Studies"),
    SeedDiagnosticTestGroup("Iron studies with Ferritin"),
    SeedDiagnosticTestGroup("Lipid profile"),
    SeedDiagnosticTestGroup("Complete Hemogram"),
    SeedDiagnosticTestGroup("Vitamin Profile"),
    SeedDiagnosticTestGroup("Diabetes profile"),
    SeedDiagnosticTestGroup("HBA1C"),
    SeedDiagnosticTestGroup("Hormones"),
    SeedDiagnosticTestGroup("CA-19.9 (Pancreatic cancer marker )"),
    SeedDiagnosticTestGroup("CA 72.4 (STOMACH CANCER MARKER)"),
    SeedDiagnosticTestGroup("CA 125 (OVARIAN CANCER MARKER )"),
    SeedDiagnosticTestGroup("CA 15.3 ( BREAST CANCER MARKER )"),
    SeedDiagnosticTestGroup("CEA (Carcino embryonic antigen )"),
    SeedDiagnosticTestGroup("PSA -Free"),
    SeedDiagnosticTestGroup("AFP"),
    SeedDiagnosticTestGroup("Insulin fasting"),
    SeedDiagnosticTestGroup("HOMA Index with Beta cells"),
    SeedDiagnosticTestGroup("Cortisol"),
    SeedDiagnosticTestGroup("Cortisol ,Serum"),
)


DIAGNOSTIC_TEST_PACKAGES: tuple[SeedDiagnosticPackage, ...] = (
    SeedDiagnosticPackage("Full body with vitamins"),
    SeedDiagnosticPackage("Full body without vitamins"),
    SeedDiagnosticPackage("Men peak performance"),
    SeedDiagnosticPackage("Women peak performance"),
)


# Diagnostic tests you provided (hemogram sample).
DIAGNOSTIC_TESTS: tuple[SeedDiagnosticTest, ...] = (
    SeedDiagnosticTest(
        test_name="Haemoglobin (Hb)",
        parameter_key="haemoglobin",
        unit="g/dL",
        meaning="Carries oxygen in blood",
        lower_range_male=13.0,
        higher_range_male=17.0,
        lower_range_female=12.0,
        higher_range_female=15.0,
        causes_when_high="dehydration, lung disease",
        causes_when_low="iron deficiency, blood loss",
        effects_when_high="headache",
        effects_when_low="tiredness",
        what_to_do_when_low="Check iron, B12, folate; improve diet",
        what_to_do_when_high="Hydrate, check lungs, smoking",
    ),
    SeedDiagnosticTest(
        test_name="Total RBC",
        parameter_key="rbc_count",
        unit="million/uL",
        meaning="Number of red blood cells",
        lower_range_male=4.5,
        higher_range_male=5.5,
        lower_range_female=3.8,
        higher_range_female=4.8,
        causes_when_high="dehydration",
        causes_when_low="anemia, bleeding",
        effects_when_high=None,
        effects_when_low="weakness",
        what_to_do_when_low="Check iron, B12",
        what_to_do_when_high="Hydrate, check cause",
    ),
    SeedDiagnosticTest(
        test_name="Haematocrit (HCT)",
        parameter_key="haematocrit_hct",
        unit="%",
        meaning="% of RBC in blood",
        lower_range_male=40.0,
        higher_range_male=50.0,
        lower_range_female=36.0,
        higher_range_female=46.0,
        causes_when_high="dehydration",
        causes_when_low="anemia",
        effects_when_high=None,
        effects_when_low="less oxygen",
        what_to_do_when_low="Improve nutrition",
        what_to_do_when_high="Drink fluids",
    ),
    SeedDiagnosticTest(
        test_name="MCV",
        parameter_key="mcv",
        unit="fL",
        meaning="Size of RBC",
        lower_range_male=83.0,
        higher_range_male=101.0,
        lower_range_female=83.0,
        higher_range_female=101.0,
        causes_when_high="B12 deficiency",
        causes_when_low="iron deficiency",
        effects_when_high="Helps identify anemia type",
        effects_when_low="Helps identify anemia type",
        what_to_do_when_low="Check iron",
        what_to_do_when_high="Check B12",
    ),
    SeedDiagnosticTest(
        test_name="MCH",
        parameter_key="mch",
        unit="pg",
        meaning="Hb per RBC",
        lower_range_male=27.0,
        higher_range_male=32.0,
        lower_range_female=27.0,
        higher_range_female=32.0,
        causes_when_high="B12 issue",
        causes_when_low="iron deficiency",
        effects_when_high=None,
        effects_when_low="iron issue",
        what_to_do_when_low="Confirm iron",
        what_to_do_when_high="Check B12",
    ),
    SeedDiagnosticTest(
        test_name="MCHC",
        parameter_key="mchc",
        unit="g/dL",
        meaning="Hb concentration",
        lower_range_male=31.5,
        higher_range_male=34.5,
        lower_range_female=31.5,
        higher_range_female=34.5,
        causes_when_high="rare",
        causes_when_low="iron deficiency",
        effects_when_high=None,
        effects_when_low="pale cells",
        what_to_do_when_low="Check iron",
        what_to_do_when_high="Check disorder",
    ),
    SeedDiagnosticTest(
        test_name="RDW",
        parameter_key="rdw",
        unit="%",
        meaning="RBC size variation",
        lower_range_male=11.6,
        higher_range_male=14.0,
        lower_range_female=11.6,
        higher_range_female=14.0,
        causes_when_high="mixed deficiency",
        causes_when_low="normal",
        effects_when_high="nutrition issue",
        effects_when_low=None,
        what_to_do_when_low="Usually none",
        what_to_do_when_high="Check iron, B12",
    ),
    SeedDiagnosticTest(
        test_name="Platelet Count",
        parameter_key="platelets",
        unit="thousand/uL",
        meaning="Clotting cells",
        lower_range_male=150.0,
        higher_range_male=410.0,
        lower_range_female=150.0,
        higher_range_female=410.0,
        causes_when_high="inflammation",
        causes_when_low="infection",
        effects_when_high=None,
        effects_when_low="bleeding risk",
        what_to_do_when_low="Avoid injury",
        what_to_do_when_high="Check cause",
    ),
    SeedDiagnosticTest(
        test_name="WBC Count",
        parameter_key="wbc_value",
        unit="thousand/uL",
        meaning="Infection cells",
        lower_range_male=4.0,
        higher_range_male=10.0,
        lower_range_female=4.0,
        higher_range_female=10.0,
        causes_when_high="infection",
        causes_when_low="weak immunity",
        effects_when_high="Infection risk",
        effects_when_low="Infection risk",
        what_to_do_when_low="Check doctor",
        what_to_do_when_high="Find infection",
    ),
    SeedDiagnosticTest(
        test_name="Neutrophils",
        parameter_key="neutrophils",
        unit="%",
        meaning="Fight bacteria",
        lower_range_male=40.0,
        higher_range_male=80.0,
        lower_range_female=40.0,
        higher_range_female=80.0,
        causes_when_high="infection",
        causes_when_low="severe illness",
        effects_when_high="Infection risk",
        effects_when_low="Infection risk",
        what_to_do_when_low="Avoid exposure",
        what_to_do_when_high="Check infection",
    ),
    SeedDiagnosticTest(
        test_name="Lymphocytes",
        parameter_key="lymphocytes",
        unit="%",
        meaning="Fight viruses",
        lower_range_male=20.0,
        higher_range_male=40.0,
        lower_range_female=20.0,
        higher_range_female=40.0,
        causes_when_high="viral",
        causes_when_low="weak immunity",
        effects_when_high="Viral response",
        effects_when_low="Viral response",
        what_to_do_when_low="Improve immunity",
        what_to_do_when_high="Monitor",
    ),
    SeedDiagnosticTest(
        test_name="Monocytes",
        parameter_key="monocytes",
        unit="%",
        meaning="Clean-up cells",
        lower_range_male=2.0,
        higher_range_male=10.0,
        lower_range_female=2.0,
        higher_range_female=10.0,
        causes_when_high="chronic infection",
        causes_when_low="Recovery phase",
        effects_when_high=None,
        effects_when_low="Recovery phase",
        what_to_do_when_low="Usually none",
        what_to_do_when_high="Check infection",
    ),
    SeedDiagnosticTest(
        test_name="Eosinophils",
        parameter_key="eosinophils",
        unit="%",
        meaning="Allergy cells",
        lower_range_male=1.0,
        higher_range_male=6.0,
        lower_range_female=1.0,
        higher_range_female=6.0,
        causes_when_high="allergy",
        causes_when_low=None,
        effects_when_high="Allergy symptoms",
        effects_when_low=None,
        what_to_do_when_low=None,
        what_to_do_when_high="Treat allergy",
    ),
    SeedDiagnosticTest(
        test_name="Basophils",
        parameter_key="basophils",
        unit="%",
        meaning="Allergy response",
        lower_range_male=0.0,
        higher_range_male=2.0,
        lower_range_female=0.0,
        higher_range_female=2.0,
        causes_when_high="inflammation",
        causes_when_low="mild",
        effects_when_high=None,
        effects_when_low="Mild",
        what_to_do_when_low=None,
        what_to_do_when_high="Check cause",
    ),
    SeedDiagnosticTest(
        test_name="SGOT (AST)",
        parameter_key="sgot_ast",
        unit="U/L",
        meaning="Liver/muscle enzyme",
        lower_range_male=3.0,
        higher_range_male=50.0,
        lower_range_female=3.0,
        higher_range_female=35.0,
        causes_when_high="liver damage",
        causes_when_low="not important",
        effects_when_high="Liver issue",
        effects_when_low=None,
        what_to_do_when_low="Not needed",
        what_to_do_when_high="Avoid alcohol, repeat test",
    ),
    SeedDiagnosticTest(
        test_name="SGPT (ALT)",
        parameter_key="sgpt_alt",
        unit="U/L",
        meaning="Liver-specific enzyme",
        lower_range_male=3.0,
        higher_range_male=50.0,
        lower_range_female=3.0,
        higher_range_female=35.0,
        causes_when_high="liver injury",
        causes_when_low="not important",
        effects_when_high="Liver damage",
        effects_when_low=None,
        what_to_do_when_low="Not needed",
        what_to_do_when_high="Improve diet, reduce alcohol",
    ),
    SeedDiagnosticTest(
        test_name="ALP",
        parameter_key="alp",
        unit="U/L",
        meaning="Liver & bone enzyme",
        lower_range_male=43.0,
        higher_range_male=115.0,
        lower_range_female=33.0,
        higher_range_female=98.0,
        causes_when_high="blockage/bone issue",
        causes_when_low="rare",
        effects_when_high="Liver/bone issue",
        effects_when_low=None,
        what_to_do_when_low="Check nutrition",
        what_to_do_when_high="Check GGT, vitamin D",
    ),
    SeedDiagnosticTest(
        test_name="Total Bilirubin",
        parameter_key="total_bilirubin",
        unit="mg/dL",
        meaning="Jaundice marker",
        lower_range_male=0.3,
        higher_range_male=1.2,
        lower_range_female=0.3,
        higher_range_female=1.2,
        causes_when_high="liver problem",
        causes_when_low=None,
        effects_when_high="Yellow skin",
        effects_when_low=None,
        what_to_do_when_low="Not needed",
        what_to_do_when_high="See doctor",
    ),
    SeedDiagnosticTest(
        test_name="Direct Bilirubin",
        parameter_key="direct_bilirubin",
        unit="mg/dL",
        meaning="Processed bilirubin",
        lower_range_male=0.0,
        higher_range_male=0.2,
        lower_range_female=0.0,
        higher_range_female=0.2,
        causes_when_high="blockage",
        causes_when_low=None,
        effects_when_high="Liver issue",
        effects_when_low=None,
        what_to_do_when_low="Not needed",
        what_to_do_when_high="Imaging needed",
    ),
    SeedDiagnosticTest(
        test_name="Indirect Bilirubin",
        parameter_key="indirect_bilirubin",
        unit="mg/dL",
        meaning="RBC breakdown",
        lower_range_male=0.0,
        higher_range_male=0.8,
        lower_range_female=0.0,
        higher_range_female=0.8,
        causes_when_high="RBC breakdown",
        causes_when_low=None,
        effects_when_high="Mild jaundice",
        effects_when_low=None,
        what_to_do_when_low="Not needed",
        what_to_do_when_high="Check blood",
    ),
    SeedDiagnosticTest(
        test_name="GGT",
        parameter_key="ggt_value",
        unit="U/L",
        meaning="Alcohol/liver enzyme",
        lower_range_male=5.0,
        higher_range_male=55.0,
        lower_range_female=5.0,
        higher_range_female=38.0,
        causes_when_high="alcohol/liver",
        causes_when_low=None,
        effects_when_high="Liver stress",
        effects_when_low=None,
        what_to_do_when_low="Not needed",
        what_to_do_when_high="Reduce alcohol",
    ),
    SeedDiagnosticTest(
        test_name="Total Protein",
        parameter_key="total_protein",
        unit="g/dL",
        meaning="Nutrition marker",
        lower_range_male=6.6,
        higher_range_male=8.3,
        lower_range_female=6.6,
        higher_range_female=8.3,
        causes_when_high="infection",
        causes_when_low="poor nutrition",
        effects_when_high=None,
        effects_when_low="Weakness",
        what_to_do_when_low="Improve diet",
        what_to_do_when_high="Check cause",
    ),
    SeedDiagnosticTest(
        test_name="Albumin",
        parameter_key="albumin",
        unit="g/dL",
        meaning="Main protein",
        lower_range_male=3.5,
        higher_range_male=5.2,
        lower_range_female=3.5,
        higher_range_female=5.2,
        causes_when_high="dehydration",
        causes_when_low="liver issue",
        effects_when_high=None,
        effects_when_low="Low immunity",
        what_to_do_when_low="Increase protein",
        what_to_do_when_high="Hydrate",
    ),
    SeedDiagnosticTest(
        test_name="Globulin",
        parameter_key="globulin",
        unit="g/dL",
        meaning="Immune protein",
        lower_range_male=3.0,
        higher_range_male=4.2,
        lower_range_female=3.0,
        higher_range_female=4.2,
        causes_when_high="infection",
        causes_when_low="weak immunity",
        effects_when_high=None,
        effects_when_low="Immune issue",
        what_to_do_when_low="Check immunity",
        what_to_do_when_high="Check infection",
    ),
    SeedDiagnosticTest(
        test_name="A/G Ratio",
        parameter_key="a_g_ratio",
        unit=None,
        meaning="Protein balance",
        lower_range_male=1.2,
        higher_range_male=2.5,
        lower_range_female=1.2,
        higher_range_female=2.5,
        causes_when_high="rare",
        causes_when_low="liver issue",
        effects_when_high=None,
        effects_when_low="Imbalance",
        what_to_do_when_low="Check liver",
        what_to_do_when_high="Monitor",
    ),
    SeedDiagnosticTest(
        test_name="Creatinine",
        parameter_key="creatinine",
        unit="mg/dL",
        meaning="Kidney waste marker",
        lower_range_male=0.6,
        higher_range_male=1.6,
        lower_range_female=0.3,
        higher_range_female=1.2,
        causes_when_high="kidney issue",
        causes_when_low="low muscle",
        effects_when_high="Kidney function issue",
        effects_when_low=None,
        what_to_do_when_low="Usually normal",
        what_to_do_when_high="Hydrate, check kidney",
    ),
    SeedDiagnosticTest(
        test_name="eGFR",
        parameter_key="egfr",
        unit=None,
        meaning="Kidney filtering",
        lower_range_male=90.0,
        higher_range_male=999.0,
        lower_range_female=90.0,
        higher_range_female=999.0,
        causes_when_high=None,
        causes_when_low="kidney disease",
        effects_when_high=None,
        effects_when_low="Poor filtration",
        what_to_do_when_low="Monitor health",
        what_to_do_when_high="Usually ok",
    ),
    SeedDiagnosticTest(
        test_name="Uric Acid",
        parameter_key="uric_acid",
        unit="mg/dL",
        meaning="Gout marker",
        lower_range_male=3.5,
        higher_range_male=7.2,
        lower_range_female=2.6,
        higher_range_female=6.0,
        causes_when_high="diet/gout",
        causes_when_low=None,
        effects_when_high="Joint pain",
        effects_when_low=None,
        what_to_do_when_low="Not important",
        what_to_do_when_high="Reduce meat, alcohol",
    ),
    SeedDiagnosticTest(
        test_name="Urea (BUN)",
        parameter_key="urea_bun",
        unit="mg/dL",
        meaning="Protein waste",
        lower_range_male=8.0,
        higher_range_male=20.0,
        lower_range_female=8.0,
        higher_range_female=20.0,
        causes_when_high="dehydration",
        causes_when_low="malnutrition",
        effects_when_high="Kidney issue",
        effects_when_low=None,
        what_to_do_when_low="Improve diet",
        what_to_do_when_high="Hydrate",
    ),
    SeedDiagnosticTest(
        test_name="Total Cholesterol",
        parameter_key="total_cholesterol",
        unit="mg/dL",
        meaning="Total fat in blood",
        lower_range_male=0.0,
        higher_range_male=200.0,
        lower_range_female=0.0,
        higher_range_female=200.0,
        causes_when_high="bad diet",
        causes_when_low="rare",
        effects_when_high="Heart risk",
        effects_when_low=None,
        what_to_do_when_low="Check nutrition",
        what_to_do_when_high="Diet, exercise",
    ),
    SeedDiagnosticTest(
        test_name="LDL",
        parameter_key="ldl",
        unit="mg/dL",
        meaning="Bad cholesterol",
        lower_range_male=0.0,
        higher_range_male=100.0,
        lower_range_female=0.0,
        higher_range_female=100.0,
        causes_when_high="junk food",
        causes_when_low=None,
        effects_when_high="Artery block",
        effects_when_low=None,
        what_to_do_when_low="Usually ok",
        what_to_do_when_high="Reduce fats, meds",
    ),
    SeedDiagnosticTest(
        test_name="HDL",
        parameter_key="hdl",
        unit="mg/dL",
        meaning="Good cholesterol",
        lower_range_male=40.0,
        higher_range_male=60.0,
        lower_range_female=40.0,
        higher_range_female=60.0,
        causes_when_high=None,
        causes_when_low="poor lifestyle",
        effects_when_high=None,
        effects_when_low="Heart risk",
        what_to_do_when_low="Exercise, good fats",
        what_to_do_when_high="Good",
    ),
    SeedDiagnosticTest(
        test_name="Triglycerides",
        parameter_key="triglycerides",
        unit="mg/dL",
        meaning="Blood fat",
        lower_range_male=0.0,
        higher_range_male=150.0,
        lower_range_female=0.0,
        higher_range_female=150.0,
        causes_when_high="sugar/alcohol",
        causes_when_low=None,
        effects_when_high="Metabolic risk",
        effects_when_low=None,
        what_to_do_when_low="Rare",
        what_to_do_when_high="Reduce sugar",
    ),
    SeedDiagnosticTest(
        test_name="Non-HDL",
        parameter_key="non_hdl",
        unit="mg/dL",
        meaning="Total bad cholesterol",
        lower_range_male=0.0,
        higher_range_male=160.0,
        lower_range_female=0.0,
        higher_range_female=160.0,
        causes_when_high="same as LDL",
        causes_when_low=None,
        effects_when_high="Heart risk",
        effects_when_low=None,
        what_to_do_when_low="Good",
        what_to_do_when_high="Diet, exercise",
    ),
    SeedDiagnosticTest(
        test_name="Cholesterol/HDL Ratio",
        parameter_key="cholesterol_hdl_ratio",
        unit=None,
        meaning="Risk ratio",
        lower_range_male=0.0,
        higher_range_male=4.4,
        lower_range_female=0.0,
        higher_range_female=4.4,
        causes_when_high="imbalance",
        causes_when_low=None,
        effects_when_high="Heart risk",
        effects_when_low=None,
        what_to_do_when_low="Good",
        what_to_do_when_high="Improve lifestyle",
    ),
)

